### PR TITLE
Moved VRHush to VRPorn scraper, fixed date regex

### PR DESCRIPTION
**Pull request by axw-pub**
Since vrhush.com uses StackPath as protection against bots the scraper kept failing. Luckily, scene data is available at vrporn.com, also.
#638 #700

### CODE REVIEW

**Comment by theRealKLH** [comment]
1. I believe VRPorn is missing quite a few videos from VRHush. 
2. I see the change you made to date regex, but what does it do differently?
3. if you want to move to different provider, you are going to have to code in that change of scene-id. OR tell everyone to wipe scenes they have that "might be missing" from the new scraper. OR prepare everyone for dupe city.

**Comment by axel-wilczek** [comment]
1. That's certainly suboptimal
2. The text to be matched is e.g. "Posted **on** Premium **on** February 18, 2022" which, using the regex `(?i)^VideoPosted on (?:Premium )?(.+)$`, returns "on February 18, 2022". Obviously, that's not a valid date format.
3. True, I can assign a different ID.

**Comment by axel-wilczek** [comment]
There are now two separate scrapers: VRHush and VRHush (VRPorn)

**Comment by axel-wilczek** [comment]
It doesn't seem to be possible to translate the vrporn scene id without a lookup to vrhush.

**Comment by theRealKLH** [comment]
> 2. The text to be matched is e.g. "Posted **on** Premium **on** February 18, 2022" which, using the regex `(?i)^VideoPosted on (?:Premium )?(.+)$`, returns "on February 18, 2022". Obviously, that's not a valid date format.

NICE ONE! clean... But we technically "don't need" it to be valid since we are doing this... 	

		`dt, _ := time.Parse("January 02, 2006", date)`

I think the regex is more to pull the right date (using VideoPosted) in the HTML. If they change from "Premium on" your regex would break.

**Comment by axel-wilczek** [comment]
Well, all scenes had a time stamp of 0001-01-01 for me. Stepping through the code, it failed at that point.

**Comment by theRealKLH** [comment]
> `time.Parse("January 02, 2006", "on February 18, 2022")` does not work

hmmm.. ok, I was "assuming" things worked and it was parsing whatever the string was for the date (using "January 02, 2006" as template). Can you give me an example of scene that gave 0001-01-01 timestamp?

**Comment by axel-wilczek** [comment]
sure, here are some examples
- [JoJo Kiss – Fucking a VR Teen Outdoor](https://vrporn.com/jojo-kiss-fucking-vr-teen-outdoor/#favpopup)
- [Stop Spying And Come Over Here!](https://vrporn.com/stop-spying-and-come-over-here/)
- [The Best Rental Ever!](https://vrporn.com/the-best-rental-ever/)
- [Come Spend New Year With Me!](https://vrporn.com/come-spend-new-year-with-me/)
- [Undercover](https://vrporn.com/undercover/)

**Comment by a18project** [comment]
Will **https://vrphub.com/category/vr-hush/** be a better source of vrhush? It has 331 scenes to date, while vrporn.com has less than 300.

**Comment by axel-wilczek** [comment]
> Will **https://vrphub.com/category/vr-hush/** be a better source of vrhush? It has 331 scenes to date, while vrporn.com has less than 300.

Possibly, the vrp scraper was already implemented, though. I could code a vrphub scraper if that's preferred @theRealKLH

**Comment by axw-pub** [comment]
I'm having trouble debugging in gitpod. The vrphub scraper might take some time.

**Comment by axw-pub** [comment]
I still can't get debugging to work in gitpod. I'd like to develop locally but I can't get air to work on windows, either.
When I started, all I wanted to do was swiftly fix the VRHush scraper but now I think I'll have to setup a linux box with remote debugging capabilities.

The new scraper seems to work fine, though. As of now, it scrapes 331 scenes. There's 332 on the page in total but I can't figure out which one is missing and why.

**Pull request merged**
