### PR TITLE
minor: add some checks for invalid data to scene edit dialog

### PR DESCRIPTION
**Pull request by crwxaj**

### CODE REVIEW

**Comment by CoolMintChocolate** [comment]
@crwxaj this is breaking `Edit scene details` button. Browser console shows this error when clicking on the button: `ReferenceError: images is not defined`. One possible way to fix this:

```
let images;
try {
  images = JSON.parse(scene.images)
} catch {
  images = []
}
```

**Comment by crwxaj** [comment]
This should already be fixed in #907

**Comment by dangmai** [comment]
#907 fixes the `scene.files` issue, this issue is about the `images` variable. It's definitely still happening on `master`.

**Comment by CoolMintChocolate** [comment]
#907 fixes the `scene.files` variable, but the `images` variable is still an issue. I tested this on the `master` branch and it's definitely still happening there.

**Comment by crwxaj** [comment]
You are right, thanks for double checking. Maybe I confused Github (or myself) with overlapping PRs. #928 should finally fix it.

**Pull request merged**
