### PR TITLE
Adds asc/desc for Last Viewed

### PR DESCRIPTION
**Pull request by yep-it-not-me**
Lets people sort by last viewed date so they can see what they haven't seen in forever. 

Includes recommended consistency change.

### CODE REVIEW

**Comment by yep-it-not-me** [comment]
Apologies for the multiple commits, was learning how to get this to build on windows. Next time I won't be using windows.

**Comment by cld9x** [comment]
@yep-it-not-me please fix option labels (they are the same atm)

**Comment by yep-it-not-me** [comment]
> @yep-it-not-me please fix option labels (they are the same atm)

I'm not sure I follow. The option labels follow existing convention, using the same text but with arrows indicating ascending or descending sort, such as "Rating" and "File added date"

**Comment by cld9x** [comment]
@yep-it-not-me yes, sorry, you're right - not sure what I had on my mind while making that comment

**Pull request merged**
