### PR TITLE
Update README.md to add command line arguments

### PR DESCRIPTION
**Pull request by diemade**
After spending 1,5 hours searching for the way to change the main port i think that the Command line arguments should be documented here.

### CODE REVIEW

**Comment by toshski** [comment]
Can you also add a column for the equivalent Environment Variable, which is more likely to be used by people using Docker. 
XBVR_APPDIR, XBVR_CACHEDIR, XBVR_IMAGEPROXYDIR, XBVR_SEARCHDIR, XBVR_VIDEOPREVIEWDIR,  XBVR_SCRIPTHEATMAPDIR, XBVR_MYFILESDIR, DATABASE_URL, XBVR_WEB_PORT, XBVR_WS_ADDR

Also, as an alternative to keep the Readme shorter, you could add a page to the Wiki and then just reference it in the readme.

**Comment by diemade** [comment]
> 
> Also, as an alternative to keep the Readme shorter, you could add a page to the Wiki and then just reference it in the readme.

There is a wiki?

**Comment by manacker** [comment]
Toshski is referring to the [Wiki feature](https://github.com/xbapps/xbvr/wiki) here on Github, which we only just recently opened for contributions.

**Comment by crwxaj** [comment]
Toshski is referring to the Wiki feature here on Github, which we only just recently opened for contributions.

**Pull request merged**
