### PR TITLE
Update App.vue

### PR DESCRIPTION
**Pull request by vt-idiot**
proper import syntax?

grasping at straws trying to figure out why 0.3.26 introduced #887

https://github.com/vitejs/vite/issues/108#issuecomment-629593212

### CODE REVIEW

**Comment by theRealKLH** [comment]
It was one of the "vue" deps... We will most likely need to go through all code and add the .vue extension to all imports.

**Comment by vt-idiot** [comment]
> It was one of the "vue" deps... We will most likely need to go through all code and add the .vue extension to all imports.

Does that include _all_ imports? Like this one: https://github.com/xbapps/xbvr/blob/37233807198873ef80b3fe0f8df1dc4476eae834/ui/src/Socket.vue#L6

**Comment by theRealKLH** [comment]
sorry.. meant to post in "issues" not in the "PR".. and should have said "most likely one of..." and "we may have to go...". Looks like this dep... https://github.com/xbapps/xbvr/pull/825 ... and to answer your question.. "I don't know".

**Comment by vt-idiot** [comment]
This is likely unnecessary and would be a whole lot of work to implement throughout the project. Closing.

**Pull request closed without merging**
