### PR TITLE
Add wishlist

### PR DESCRIPTION
**Pull request by alexnsfw**
This PR adds a wishlist. It's just like the watchlist or favourites, except:
* available scenes cannot be added to it; and
* when a scene becomes available, it's removed from the wishlist.

### CODE REVIEW

**Comment by maxcom99** [comment]
Can this please be merged in?

**Comment by alexnsfw** [comment]
> Can this please be merged in?

I'm still holding out hope 2 years later...

Maintainers, is there a chance?
(@crwxaj maybe?)

**Comment by crwxaj** [comment]
To be honest I haven't really considered it. This PR was from before I was at the helm.
I'm not really against it, but couldn't this be easily emulated with a "Watchlist" and "Not downloaded" filter?

**Comment by alexnsfw** [comment]
> couldn't this be easily emulated with a "Watchlist" and "Not downloaded" filter?

That'll get you pretty close (I think that's what I used to do before implementing this), but it's not quite the same. Personally, I add scenes to my wishlist that I don't necessarily want to be in my watchlist when I do download them. Plus I like having the different color toggle button and the one-click wishlist filter.

**Pull request merged**
