### PR TITLE
Add support for unmatched files in DeoVR

### PR DESCRIPTION
**Pull request by jrebey**

### CODE REVIEW

**Comment by cld9x** [comment]
Good stuff, but file needs to be checked for availability (same as scene), so we won't be showing files that can't be played

**Comment by jrebey** [comment]
Those aren’t fields in the File struct. Is that something we should add? The closest thing we have in current state is checking the volume availability.

**Comment by cld9x** [comment]
Yes, this is what needs to be checked - volume needs to be available when it's local (it doesn't matter for cloud volumes)

**Comment by jrebey** [comment]
I didn't see a way of doing this in gorm via sql (determine if it's local and only filter available volumes if local). If you know of a way to do it, please let me know.

**Comment by cld9x** [comment]
It's good enough for now!

**Pull request merged**
