### PR TITLE
Fixes duped actors for RealJamVR & PorncornVR

### LINKED ISSUE #1570: PornCornVR/RealJamVR duplicating Actors in a Scene
When scraping PornCornVR it adds the same actors twice, but with different names. Probably because it has another link on it's description to an actor page.

E.g.: https://porncornvr.com/scene/threesome-passion-girls-prefer-anal/
[Jennifer Mendez](https://porncornvr.com/actor/jennifer-mendez/), [Katy Rose](https://porncornvr.com/actor/katy-rose/) - [Katy Rose VR model](https://porncornvr.com/actor/katy-rose/), [Jennifer Mendez VR celebrity](https://porncornvr.com/actor/jennifer-mendez/) 

https://porncornvr.com/scene/orgy-with-pizza-delivery-guy/
[Jackie Hoff](https://porncornvr.com/actor/jackie-hoff/), [Natalie Brooks](https://porncornvr.com/actor/natalie-brooks/), [Raven Lane](https://porncornvr.com/actor/raven-lane/) - [Jackie Hoff VR star](https://porncornvr.com/actor/jackie-hoff/), [Natalie Brooks VR sweetie](https://porncornvr.com/actor/natalie-brooks/), [Raven Lane VR ideal](https://porncornvr.com/actor/raven-lane/)

EDIT: The same is happening to RealJamVR

https://realjamvr.com/scene/doctors-exam-ava-stone/
[Ava Stone](https://realjamvr.com/actor/ava-stone/) - [Ava Stone VR model](https://realjamvr.com/actor/ava-stone/)

### PR DESCRIPTION
**Pull request by theRealKLH**
resolves #1570

### CODE REVIEW

**Comment by tosh6072** [comment]
I was going to look at #1570 but I assume this fixes it.

**Comment by theRealKLH** [comment]
I did not look at PornCornVR, but yes this fixes the "dupes" for RealJam. Only the four scenes (12/29 - 01/10) get dupes removed. If newer scenes are released before xbvr release, will need to update the PR.

**Comment by theRealKLH** [comment]
This should resolve #1570

**Comment by toshski** [comment]
I was going to grab a copy of this to merge into my build, but I noticed a couple of references to your github therealklh repository om api/options.go and navbar.vue.

**Comment by theRealKLH** [comment]
I HATE Github sometimes!

**Pull request closed without merging**
